### ISSUE TITLE
Für die FAQs: srsurl jetzt Pflicht

### ISSUE THREAD

**Issue by skaramuz** [harald-herberth/nutab#1]
Hallo Harald,
vielleicht kannst du in die FAQs noch aufnehmen, dass die Angabe des srsurl-Parameters jetzt Pflicht ist. Bisher hat er automatisch die URL der BHV-NuLiga-Installation genommen, oder?

Viele Grüße und Dank für deine Arbeit
Sebastian // SG Schwabach/Roth - SC 04 Schwabach Handball ;)

**Comment by harald-herberth** [comment]
Habe ich gleich als erstes Q&A aufgenommen.
