### ISSUE TITLE
Konnte Tabelle bei NuLiga nicht finden/Keine Spiele im Zeitraum gefunden

### ISSUE THREAD

**Issue by Bolli1957** [harald-herberth/nutab#10]
Hallo Allerseits,
Habe nach Empfehlung von Harald die neue Version installiert. Leider werden die im Titel genannten Fehler weiterhin angezeigt.
Bin leider nicht so in dem Thema und bin mir daher nicht sicher ob ich alles richtig gemacht habe.
Könnte mir eventuell jemand helfen?
Wenn ja, würde ich die FTP Zugangsdaten zur Verfügung stellen.
Danke im Voraus
Reinhard

**Comment by skaramuz** [comment]
Das liegt vermutlich an der Absage sämtlicher Handballspiele, nicht an der
Technik :)

Am Fr., 13. März 2020 um 19:45 Uhr schrieb Bolli1957 <
notifications@github.com>:

**Comment by Bolli1957** [comment]
Gute Idee, leider ist es nicht so. Die Daten (Spiele) stehen noch in NuLiga. Auch die Tabellen werden auf NuLiga noch angezeigt. Leider nicht auf unserer Homepage. 
Das Problem wurde auch schon hier besprochen. https://github.com/harald-herberth/nutab/issues/9
Leider hilft mir das ganze nicht. Noch eine Idee?

**Comment by skaramuz** [comment]
Hast du alle Dateien aus dem Repository ersetzt und auch den Unterordner
/Requests-1.7.0/ hochgeladen?

Schicke mir mal eine PN an skaramuz@protonmail.com.

Viele Grüße!

Am Fr., 13. März 2020 um 20:30 Uhr schrieb Bolli1957 <
notifications@github.com>:

**Comment by skaramuz** [comment]
Hallo zusammen,
das Issue kann geschlossen werden, haben es direkt geklärt.

Viele Grüße!
