### ISSUE TITLE
Fehler Ausgabe: Keine URL angegeben

### ISSUE THREAD

**Issue by Bolli1957** [harald-herberth/nutab#12]
Oben genannte Fehlermeldung tritt auf bei Spielen einzelner Mannschaften oder ganzer Liga.

Auf der Seite https://www.thc-westerkappeln.de/mannschaften/1-herren unter "Spiele der 1. Herren" und "Liga" tritt der Fehler auf.

Hier der Code
[Code.txt](https://github.com/harald-herberth/nutab/files/4332365/Code.txt)

Danke
Jemand eine Idee

**Comment by harald-herberth** [comment]
Du verwendest den Link auf teamtable (team Seite). Diese wird laut Doku nicht unterstützt.
Siehe auch Duplicate of #5
Bitte eine Link auf die Staffel (srsPlan) und auf die Mannschaft (srsVerein) einschränken.

**Comment by Bolli1957** [comment]
Hallo Harald,
vielen Dank für die Unterstützung und dein Arbeit. Problem ist gelöst.
