### ISSUE TITLE
Verlinkung Halle

### ISSUE THREAD

**Issue by tvk-handball** [harald-herberth/nutab#15]
Moin,
gibt es eine Möglichkeit die Halle (Name und/oder Nummer) mit der entsprechenden NuLiga-Seite zu verlinken, so dass man auch die Anschrift herausfinden kann ?

Also z.B. Hallen-Nr 4410 auf https://hvniederrhein-handball.liga.nu/cgi-bin/WebObjects/nuLigaHBDE.woa/wa/courtInfo?federation=HVNiederrhein&roundTyp=0&championship=RR+19%2F20&location=32162

**Comment by harald-herberth** [comment]
Das Thema Adresse der Halle taucht regelmäßig auf. Ich selber habe das nicht für so wichig erachtet, ist ja für eine werbefreie Kompaktdarstellung, und nicht eine komplette Information und Navigation. Und die meisten wissen wo die Hallen sind, sind ja meistens nicht das erste mal da.

Der Link könnte einfach geparsed werden, und über den @feld Trick dann auch zum klicken hinterlegt werden. Dann landet man aber auf nuLiga Seite, und von dort muss man in den Routenplaner, und das auf dem Handy ist nicht hübsch gelöst, da muss man seine Start-Adresse eingeben, ...

Wenn man das richtig machen will, muss man die Adresse rausparsen und einen direkten Link auf zB Google Maps machen. Das aber wiederrum erfordert einen weiteren Seitenaufruf, einen Cache für hallen, ...

Vielleichtet findet sich jemand das hübsch zu lösen über einen PR?

**Comment by tvk-handball** [comment]
mein Sohn hat in der aktuellen Saison den Verein (und damit auch den Kreis) gewechselt – somit ganz viele neue Hallen. In der kommenden Saison spielt die Mannschaft evtl. Ober-/Nordrheinliga – sprich wieder neue Hallen.

Im Jugendbereich gibt es generell immer wieder Neu-/Quereinsteiger, auch dort kennen die Eltern die Hallen meist nicht. Und die Trainer kennen zwar die Hallen, müssen aber bei dem Thema Adresse häufig passen.

Wäre daher "nice to have"

Anzeige der Adresse wäre daher schon prima, ein direkter Link zu Google-Maps müsste nicht unbedingt sein.

Hab leider keine Ahnung von PHP-Programmierung, sonst würde ich mich selbst dransetzen
