### ISSUE TITLE
ParserError nach Update

### ISSUE THREAD

**Issue by ChristianProell** [harald-herberth/nutab#17]
Hallo Zusammen,

ich habe zur neuen Saison festgestellt, dass bei all meinen Tabellen und Plänen "Konnte Tabelle nicht finden" stand.

Habe also die Daten aus dem Repository neu gezogen und eingespielt. Jetzt erhalte ich als Ergebnis "Error in GET srsTab: parsererror"

Hat irgendwer eine Ahnung, wo da der Fehler liegt?

Beste Grüße,
Christian

**Comment by Bolli1957** [comment]
Schau mal hier:
https://github.com/harald-herberth/nutab/issues/12

**Comment by Bolli1957** [comment]
oder hier
https://github.com/harald-herberth/nutab/issues/10
