### ISSUE TITLE
Liga Name umwandeln

### ISSUE THREAD

**Issue by Bolli1957** [harald-herberth/nutab#18]
Hallo,
benötige mal Hilfe.

Kann man den Liga Name umwandeln in z.B. 1. Herren?

Gruß und Danke
Reinhard

**Comment by harald-herberth** [comment]
Würde das über srsTitle gehen?

**Comment by Bolli1957** [comment]
Hallo Harald, ich glaube das geht nicht. Ich möchte innerhalb der Tabelle den Namen ändern.
Beispiel
https://thc-westerkappeln.de/spielbetrieb/die-naechsten-spiele
hier zumm Beispiel LK WE M in 1. Herren umwandeln.
Oder interpretiere ich deine Antwort falsch.
Gruß
Reinhard

**Comment by harald-herberth** [comment]
Stimmt. Staffel in der Spalte des Spielplanes lässt sich nicht ändern.
