### ISSUE TITLE
srsTab bekommt Fehler Cross-Origin Anfrage blockiert

### ISSUE THREAD

**Issue by matthiaskrause** [harald-herberth/nutab#28]
Hallo zusammen,
ich hoffe ihr könnt mir helfen. Seit heute bekomme ich auf unserer Seite z.B. bei https://sg-sued-blumenau.de/team_aktuelles.php?team=01damen1&sparte=senioren die Tabelle und die letzten Ergebnisse nicht mehr angezeigt.
In der Konsole bekomme ich einen Fehler:
`Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://www.sg-sued-blumenau.de/nutab/fetch_table.php?url=https%3A%2F%2Fbhv-handball.liga.nu%2Fcgi-bin%2FWebObjects%2FnuLigaHBDE.woa%2Fwa%2FgroupPage%3Fchampionship%3DOB+2021%2F22%26group%3D273439&verein=Blumenau&keineak=1&keineex=1&tabellenspalten=Platz%3BTeam_Kurzname%3BDiffTore%3BPlusPunkte%2B%25%3A%2BMinusPunkte&tabellenformat=l%3Bl%3Bc%3Bc&_=1652256470529. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 200.`
Kann mir jemand sagen was das bedeutet und wie ich das beheben kann?
Danke

**Comment by matthiaskrause** [comment]
Das Problem konnte ich finden, allerdings bekomme ich aktuell gerade den Fehler:
`Uncaught TypeError: data.Aktueller_Spielplan is undefined.`
Kann es sein das da gerade beim BHV an den Datenstrukturen gearbeitet wird?

**Comment by matthiaskrause** [comment]
@harald-herberth , 
Fehler 1 lag daran das die Seite sowohl mit als auch ohne www aufrufbar ist, somit kam es zu der Cross-Origin Anfrage.
Fehler2 hängt irgendwie mit dem Cache zusammen, wenn ich den deaktiviere geht es.
ABER:
Es funktioniert alles nur Lokal auf meinem Webserver, wenn ich das auf den Webspace lade funktioniert es nicht.
Ich habe auch die fetch_table.php direkt aufgerufen:
`http://localhost/blumenau/nutab/fetch_table.php?club=30447&alle=1&spielplanverein=1` 
Hier kommt der Spielplan wunderbar zurück.
Wenn ich die gleiche fetch_table.php auf dem Server (https://www.sg-sued-blumenau.de/nutab/fetch_table.php?club=30447&alle=1&spielplanverein=1) aufrufe kommt folgender Fehler:
`Fatal error: Uncaught Requests_Exception: cURL error 28: Connection timeout after 10003 ms in /mnt/web211/e3/72/54217772/htdocs/nutab/Requests-1.7.0/library/Requests/Transport/cURL.php:422 Stack trace: #0 /mnt/web211/e3/72/54217772/htdocs/nutab/Requests-1.7.0/library/Requests/Transport/cURL.php(177): Requests_Transport_cURL->process_response() #1 /mnt/web211/e3/72/54217772/htdocs/nutab/Requests-1.7.0/library/Requests.php(379): Requests_Transport_cURL->request() #2 /mnt/web211/e3/72/54217772/htdocs/nutab/Requests-1.7.0/library/Requests.php(231): Requests::request() #3 /mnt/web211/e3/72/54217772/htdocs/nutab/fetch_table.php(186): Requests::get() #4 /mnt/web211/e3/72/54217772/htdocs/nutab/fetch_table.php(291): NuLiga->get() #5 {main} thrown in /mnt/web211/e3/72/54217772/htdocs/nutab/Requests-1.7.0/library/Requests/Transport/cURL.php on line 422 `

Hast du eine Idee an was das liegen könnte?
Vielen Dank schon mal für die Hilfe

**Comment by snoopotic** [comment]
Das scheint ein Strato-Setting zu sein/machen. Ich habe das auch bei uns im Verein.

**Comment by matthiaskrause** [comment]
Kannst du mir sagen wie deine Seite heißt?
Hast du eine Lösung dafür gefunden?
Laut Strato wurde an den Webservern nichts geändert...sagt zumindest deren Support.

**Comment by FeldeMathi** [comment]
gibt es schon Neuigkeiten hier?

**Comment by matthiaskrause** [comment]
Ich habe ein Ticket bei Strato.
Es wäre aber gut wenn du das ebenfalls melden könntest, da wächst dann der Druck.
Standardmäßig sagen die erstmal das nichts geändert wurde, glaube ich aber nicht.

**Comment by FeldeMathi** [comment]
kannst du mir den Inhalt des Tickets nennen? dann mache ich das analog auf

**Comment by matthiaskrause** [comment]
Na ja, du findest ja in deinen Error Logs auch eine Meldung das der Aufruf einen Timeout erhält oder? Und das erst seit kurzem. Um welche Seite geht es den bei dir? Du kannst gerne auf mein Ticket Bezug nehmen, Nr. 2022051901001055

**Comment by FeldeMathi** [comment]
Hi Matthias - hattest du schon eine Lösung bekommen?

**Comment by matthiaskrause** [comment]
Ja, die Lösung war den Provider zu wechseln :-)
Leider konnte bzw. wollte Strato mir nicht helfen, bin jetzt zu Hetzner und da funktioniert alles wie gehabt.
