### ISSUE TITLE
Problem bei Spielplananzeige

### ISSUE THREAD

**Issue by DerMars93** [harald-herberth/nutab#3]
Hallo Harald,

ich habe den Spielplan bei mir eingebunden habe allerdings das Problem, dass das erste angezeigte Spiel nicht vom angegebenen Team ist. Heißt in den Parametern wird Team A angegeben, das erste Spiel im Plan enthält allerdings Team B und Team C. Team A wird auch definitiv selektiert, da danach nur noch die Spiele von Team A angezeigt werden. 

Das zweite "Problem" ist die Anzeige des Spielplans. Ist es irgendwie möglich, das das in den Parametern angegebene Team A ausgeblendet werden kann, sodass egal ob Heim oder Auswärts nur die gegnerische Mannschaft angezeigt werden kann?

Vielleicht hast du hier ja Ideen zu. Vielen Dank im Voraus.

Beste Grüße

**Comment by harald-herberth** [comment]
Steht schon lange auf meinem Backlog (die Anzeige nur des Gegners). Schafft es aber nicht nach vorne. Vielleicht will das jemand anders versuchen wenn es (auch anderen) dringend und wichtig ist?
