### ISSUE TITLE
Neue PHP Version 

### ISSUE THREAD

**Issue by allgaeuer13** [harald-herberth/nutab#33]
Hallo, hab heute bei Strato die php Version 7.4 auf die Version 8 geändert, da die 7.4 anscheinend kostenpflichtig werden soll.
Leider funktionierte danach meine Homepage nicht mehr und ich musste die Version zurücknehmen. Kann leider nicht sagen ob es an WordPress liegt oder nutab das Problem verursacht. Hat jemand ähnliche Erfahrungen?

**Comment by Eclipse16V** [comment]
Wir nutzen die neusten Version von WP, WooCommerce und PHP 8.1. Keine Probleme. Alles funktioniert, auch nuliga. Vielleicht erst mal alle Plugins und das Theme aktualisieren und in der Gehlermeldung schauen ob diese von einem nicht kompatiblen plugin oder theme kommt.

**Comment by allgaeuer13** [comment]
Ok Danke. Dann aktualisiere ich mal alles und lösche auch den Cache. Hoffentlich hilft das.
