### ISSUE TITLE
Halle nicht nur als Zahl ?

### ISSUE THREAD

**Issue by xstreamon** [harald-herberth/nutab#4]
Hallo,

ist eigentlich kein Issue, sondern eher ein feature. Aber ist es machbar, das der Spielort (Halle)
nicht nur als Zahl angegeben wird ?

vielen Dank....

**Comment by xTilion** [comment]
Würde ich mir auch wünschen, habe mir den Request an NuLiga mal angeschaut, da wird zwar nach Halle_Abk etc. gefragt, jedoch nur die Hallennummer zurückgegeben.

**Comment by Eclipse16V** [comment]
Würde ich auch gut finden. Wer weiß wo und wie die Nummern zu finden sind bzw. die Halle heißt, für den ist es einfach. Für die älteren unter uns schon etwas schwieriger.

**Comment by mattg2** [comment]
+1 :-)

**Comment by mattg2** [comment]
Hab es mit der Halle hinbekommen und Pullrequest gestellt.
#7

**Comment by harald-herberth** [comment]
Werde das über den PR einarbeiten.
