### ISSUE TITLE
Teamdarstellung auch für Handball möglich?

### ISSUE THREAD

**Issue by hella-schu** [harald-herberth/nutab#5]
Lieber Harald,

in der Dokumentation steht, Teamseiten seien nur für Tennis möglich. Beim Handball gäbe es ja auch Teamseiten, allerdings heisst der Parameter da teamtable und nicht nur team. Wie hier z.B.:
https://bhv-handball.liga.nu/cgi-bin/WebObjects/nuLigaHBDE.woa/wa/groupPage?championship=OB+2019%2F20&group=246027

Wäre das auch machbar?

Danke und viele Grüße
Hella

**Comment by harald-herberth** [comment]
Hallo,
die Teamseite bei Handball ist bekannt. Ich erkenne nur nicht, welchen Mehrwert sie bietet gegenüber der Spielplananzeige einer Staffel eingeschränkt auf eine Mannschaft. Die Zusatzinformation über Verein, Spielleiter etc. plane ich eh nicht auch noch zu verarbeiten. Soll ja keine Konkurrenz zu nuLiga werden, sondern nur eine Ergänzung um Einfach an Tabellen und Spielpläne zu kommen. Und das einfach bezieht sich auch nur auf die Anwendung. Die Erstellung ist schon kompliziert genug geworden, auch weil die anderen Sportarten mit aufgenommen wurden.
