### ISSUE TITLE
srstabellenkopf und srstabellenspalten

### ISSUE THREAD

**Issue by xstreamon** [harald-herberth/nutab#8]
Ich muss hier noch mal dran. Erstmal vielen Dank. Aber ich habe noch ein Problem mit dem einbau.

Bislang habe ich es recht einfach gehalten :

`<div class="srsPlanVerein" srsVerband="hvn-handball" srsClub="75069" srsTitle="letzter und nächster Spieltag" srsAlle=0 srsVon=7 srsBis=7 srsNeueVorne=1 srsOhneHalle=1 srsClass="zentrierte-tabelle" srsKeineEx=1></div>`

Nun ist es ja mit der Halle als namen möglich also habe ich srsOhneHalle=1 entfernt.
Dann war da erst wieder die Nummer. :(
Also weiter eingelesen und nun zu dem gekommen.

`<div class="srsPlanVerein" srsVerband="hvn-handball" srsClub="75069" srsTitle="Spieltag" srsAlle=0 srsVon=7 srsBis=7 srsNeueVorne=1 srsClass="zentrierte-tabelle" srsKeineEx=1 srstabellenformat="l;l;l;l;l" srstabellenkopf="Datum;Halle;Heim;Gast;**Ergebnis**" srstabellenspalten="Wochentag+%, +SpieldatumTag/^..(..).(..).(..)$/$3.$2.$1+% +Spieldatum!11!5;Halle_Name_kurz;HeimTeam_Name_lang;GastTeam_Name_lang;**?????**"</div>`

Aber wie bekomme ich das Ergebis eingefügt, am besten so wie es im Standart war (mit link)

bzw. Kann jemand den kopf und die spalten so posten, wie es standart mässig gemacht wird, wenn man es nicht selbst definiert. Dann kann ich mir den passenden Teil da raus nehmen.

**Comment by xstreamon** [comment]
Und kann man in der Tabelle auch eigenen Text einfügen. Ich würde zum beispiel zwischen Heim und Gast gerne noch eine Spalte mit ":" haben.

**Comment by mattg2** [comment]
keine Ahnung, ob Dir das was hilf, auf hsg-infos.de ist oben rechts eine Ergebnisliste und die ist so aufgebaut:
<div class="srsPlanVerein" srsurl="https://hhv-handball.liga.nu/cgi-bin/WebObjects/nuLigaHBDE.woa/wa/clubInfoDisplay?club=70124"  srsVerband="hhv-handball" srsClub="70124"  srsvon="16" srsbis="0" srsNeueVorne=1 srstabellenformat="l;l;l;l;c" srstabellenkopf="-" srstabellenspalten="SpieldatumTag/^..(..).(..).(..)$/$3.$2.$1;Liga_Name_kurz;HeimTeam_Name_lang!0!25;GastTeam_Name_lang!0!25;Heim+%:+Gast" srsMaxZeilen=6
