### ISSUE TITLE
Änderung nuLiga?

### ISSUE THREAD

**Issue by abroess** [harald-herberth/nutab#9]
Moin!
Kann es sein, dass nuLiga gestern eine Änderung eingeführt hat? Alle Abfragen (Handball) laufen seit heute ins leere mit der Fehlermeldung "Konnte Tabelle bei NuLiga nicht finden" bei den Tabellen bzw. beim Spielplan "Keine Spiele im Zeitraum gefunden".

**Comment by harald-herberth** [comment]
Ja, so ist es. Werde dem Problem nachgehen und hoffe auf eine schnelle Korrektur in einer neuen Release.

**Comment by matthiaskrause** [comment]
Hallo Harald, ich habe das gleiche Problem, hoffentlich lässt es sich leicht und vor allem bald beheben.
Danke schon mal für deine Ursachenforschung.

**Comment by harald-herberth** [comment]
nuLiga unterstützt http nicht mehr. Das uralt Snoopy kommt mit https wohl nicht zurecht. Muss schauen ob Snoopy einen schnellen Fix hat, oder ob ich gleich auf request umstellen soll, war eh auf dem Backlog.
Falls jemand einen schnellen Fix hat, bitte per PR an mich.

Und bitte keine Kommentare mit "ich habe das Problem" auch. Jeder hat derzeit das Problem. Macht nur meine Bandbreite dicht.

**Comment by harald-herberth** [comment]
Hoffe das v0.0.16 das fixed.
Bitte um Rückmeldung wenn ja oder nein, wobei bitte nicht alle;-)

**Comment by mjasny** [comment]
@harald-herberth funktioniert wunderbar! Danke :) Habe auch schon mein wp-plugin dazu geupdated.

**Comment by Jens-MM** [comment]
Hallo Harald,

funktioniert perfekt. Danke!!!

**Comment by abroess** [comment]
Perfekt! Vielen Dank!

**Comment by Bolli1957** [comment]
Hallo allerseits,
habe die neue Version installiert, leider funktioniert es bei mir nicht.
Bin mir aber auch nicht sicher ob ich alles richtig gemacht habe.
Kann mir eventuell jemand helfen?
Wenn ja, würde ich die FTP Zugangsdaten nennen.
Gruß
Reinhard
